# Site Information
site_name: Technical Documentation
site_url: https://yourdomain.com
site_author: Rajesh Bhola
site_description: A comprehensive guide to Java, Spring Boot, Microservices, SQL, and Kafka

# Repository
repo_name: username/repo
repo_url: https://github.com/username/repo
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Rajesh Bhola

# Theme Configuration
theme:
  name: material
  language: en

  # Color Palette
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Typography
  font:
    text: Roboto
    code: Roboto Mono

  # Features
  features:
    # Navigation
    - navigation.instant        # Instant loading
    - navigation.instant.progress  # Progress indicator
    - navigation.tracking       # URL tracking
    - navigation.sections      # Navigation sections
    - navigation.expand        # Expand navigation by default
    - navigation.path          # Breadcrumbs
    - navigation.indexes       # Section index pages
    - navigation.top           # Back to top button
    - navigation.footer        # Footer navigation

    # Table of Contents
    - toc.follow               # TOC follows scroll
    - toc.integrate            # Integrated TOC

    # Search
    - search.suggest           # Search suggestions
    - search.highlight         # Highlight search results
    - search.share             # Share search results

    # Header
    - header.autohide          # Auto-hide header

    # Content
    - content.code.copy        # Copy code button
    - content.code.annotate    # Code annotations
    - content.tabs.link        # Link content tabs
    - content.tooltips         # Tooltips

  # Icons
  icon:
    repo: fontawesome/brands/github
    logo: material/library

  # Favicon
  favicon: assets/favicon.png

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: en

  - tags

  # - social:
  #     cards: true
  #     cards_layout_options:
  #       background_color: "#1e40af"
  #       color: "#ffffff"

  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      permalink_title: Anchor link to this section

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
      format: svg
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Extra CSS and JavaScript
extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra Configuration
extra:
  # Remove "Made with Material for MkDocs" footer
  generator: false

  # Social Links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/username
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/username
      name: Twitter
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/username
      name: LinkedIn
    - icon: fontawesome/solid/paper-plane
      link: mailto:your.email@example.com
      name: Email

  # Analytics (feedback section removed)
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX

  # Version Provider
  version:
    provider: mike
    default: stable

# Navigation
nav:
  - Home: index.md
  - Java:
    - Basics:
      - Keywords: java/basics/keywords.md
      - Identifiers: java/basics/identifiers.md
    - OOPs:
      - Overview: java/oops/index.md
    - Exception Handling:
      - Overview: java/exception-handling/index.md
  - Spring Boot:
    - Overview: springboot/basics/index.md
  - Microservices:
    - Overview: microservices/index.md
  - SQL:
    - Overview: sql/index.md
  - Kafka:
    - Overview: kafka/index.md
